### ISSUE TITLE
Unable to create an app: unable to connect to rabbit mq server

### ISSUE THREAD

**Issue by jonpugh** [terra-ops/terra_ui_module#1]
I am using the Vagrantfile in terra-ops/terra-api to create a server with rabbitmq, etc.

Then I'm using terra manually to add the UI app I created at https://github.com/terra-ops/terra-ui-prototype.

This enables and installs your module, and sets the amqp_server config. The drupal site works and the app and environment content types are there, but submitting an app results in:

```
PhpAmqpLib\Exception\AMQPRuntimeException: Error Connecting to server(110)
```

I don't know anything about RabbitMQ and couldn't find any config files in /etc/rabbitmq or any other place, so I could be missing something.

Otherwise, this is AWESOME.  looking forward to getting it working!!

thanks!

**Comment by jonpugh** [comment]
Doh! 

I just realized that the rabbitMQ server is on the host, so it won't be reachable at localhost...

Will try something else and report back!

**Comment by jonpugh** [comment]
OK!! I got it to work!

I was able to use the RabbitMQ docker container and terra itself to launch it!

As long as the ports are exposed to the host, receiver can run on the host no problem.

See https://github.com/terra-ops/terra-ui-prototype

Note: The automatic saving of AMQ server setting is not working. Set that manually, using "queue" as the host.

Should have that working soon.

NICE.

**Comment by jonpugh** [comment]
oh my goodness this is amazing!!

**Comment by jlyon** [comment]
Nice!

**Comment by jonpugh** [comment]
So, I've moved the receiver.php code into the new terra CLI command `terra queue` (and gave you commit credit). See https://github.com/terra-ops/terra-cli/commit/8ecb66d99ca3a52b5d9405fcdb74c37f89adc783

This command takes an argument so you can specify a different rabbitMQ server to poll.

This makes the whole setup really easy now!

```
$ terra app:add ui https://github.com/terra-ops/terra-ui-prototype.git
$ terra env:a ui local --enable=1
```

With these two commands, you'll get a rabbitMQ container, the drupal site will install itself, give you a login link.  Go create an App node, then go create an Environment node.

Then, visit your rabbitMQ server at http://local.computer:8080, login with guest guest.  You will see the commands: "Ready: 2".

Then, simply run:

```
$ terra queue
```

And terra will pull the commands from RabbitMQ and run them!

That's it.

Excellent work, @jlyon .

P.S. The domain local.computer resolves to the default boot2docker IP, making it easy on our Mac using friends.  If you are using linux, you might want to add to your hosts file so you can use the same domains.

Thanks!

**Comment by jonpugh** [comment]
Closing this, it's all documented in the https://github.com/terra-ops/terra-ui-prototype repo.
